// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package config

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadConfig returns the embedded CollectionSpec for config.
func loadConfig() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ConfigBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load config: %w", err)
	}

	return spec, err
}

// loadConfigObjects loads config and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*configObjects
//	*configPrograms
//	*configMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadConfigObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadConfig()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// configSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type configSpecs struct {
	configProgramSpecs
	configMapSpecs
	configVariableSpecs
}

// configProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type configProgramSpecs struct {
}

// configMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type configMapSpecs struct {
}

// configVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type configVariableSpecs struct {
}

// configObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadConfigObjects or ebpf.CollectionSpec.LoadAndAssign.
type configObjects struct {
	configPrograms
	configMaps
	configVariables
}

func (o *configObjects) Close() error {
	return _ConfigClose(
		&o.configPrograms,
		&o.configMaps,
	)
}

// configMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadConfigObjects or ebpf.CollectionSpec.LoadAndAssign.
type configMaps struct {
}

func (m *configMaps) Close() error {
	return _ConfigClose()
}

// configVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadConfigObjects or ebpf.CollectionSpec.LoadAndAssign.
type configVariables struct {
}

// configPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadConfigObjects or ebpf.CollectionSpec.LoadAndAssign.
type configPrograms struct {
}

func (p *configPrograms) Close() error {
	return _ConfigClose()
}

func _ConfigClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed config_bpfeb.o
var _ConfigBytes []byte
