// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package config

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadConfiguration returns the embedded CollectionSpec for configuration.
func loadConfiguration() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ConfigurationBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load configuration: %w", err)
	}

	return spec, err
}

// loadConfigurationObjects loads configuration and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*configurationObjects
//	*configurationPrograms
//	*configurationMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadConfigurationObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadConfiguration()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// configurationSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type configurationSpecs struct {
	configurationProgramSpecs
	configurationMapSpecs
	configurationVariableSpecs
}

// configurationProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type configurationProgramSpecs struct {
}

// configurationMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type configurationMapSpecs struct {
}

// configurationVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type configurationVariableSpecs struct {
}

// configurationObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadConfigurationObjects or ebpf.CollectionSpec.LoadAndAssign.
type configurationObjects struct {
	configurationPrograms
	configurationMaps
	configurationVariables
}

func (o *configurationObjects) Close() error {
	return _ConfigurationClose(
		&o.configurationPrograms,
		&o.configurationMaps,
	)
}

// configurationMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadConfigurationObjects or ebpf.CollectionSpec.LoadAndAssign.
type configurationMaps struct {
}

func (m *configurationMaps) Close() error {
	return _ConfigurationClose()
}

// configurationVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadConfigurationObjects or ebpf.CollectionSpec.LoadAndAssign.
type configurationVariables struct {
}

// configurationPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadConfigurationObjects or ebpf.CollectionSpec.LoadAndAssign.
type configurationPrograms struct {
}

func (p *configurationPrograms) Close() error {
	return _ConfigurationClose()
}

func _ConfigurationClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed configuration_bpfeb.o
var _ConfigurationBytes []byte
